---
driver:
  name: vagrant
  provider: parallels

provisioner:
  product_name: chef
  install_strategy: always

verifier:
  name: inspec
  sudo: true
  inspec_tests:
  - test/integration/default

platforms:
- name: el-capitan-chef13
  driver:
    box: apex/macos-10.11.6
  provisioner:
    product_version: 13

- name: el-capitan-chef14
  driver:
    box: apex/macos-10.11.6
  provisioner:
    product_version: 14

- name: sierra-chef13
  driver:
    box: apex/macos-10.12.6
  provisioner:
    product_version: 13

- name: sierra-chef14
  driver:
    box: apex/macos-10.12.6
  provisioner:
    product_version: 14

- name: high-sierra-chef13
  driver:
    box: apex/macos-10.13.4
  provisioner:
    product_version: 13

- name: high-sierra-chef14
  driver:
    box: apex/macos-10.13.4
  provisioner:
    product_version: 14

suites:
- name: default
  run_list:
  - recipe[macos::disable_software_updates]
  - recipe[macos_test::preferences]
  verifier:
    controls:
    - dock-appearance
    - show-all-files
    - updates-disabled

- name: power-management
  provisioner:
    multiple_converge: 2
  run_list:
  - recipe[macos::keep_awake]
  verifier:
    controls:
    - screensaver-disabled
    - remote-administration
    - no-sleep

- name: machine-name
  run_list:
  - recipe[macos_test::machine_name]
  verifier:
    controls:
    - nonstandard-computer-name

- name: spotlight
  run_list:
  - recipe[macos_test::spotlight]
  verifier:
    controls:
    - indexing-and-searching

- name: xcode
  run_list:
  - recipe[macos_test::xcode]
  verifier:
    controls:
    - xcode-and-simulators

- name: xcode-beta
  run_list:
  - recipe[macos_test::xcode_beta]
  verifier:
    controls:
    - xcode-beta

- name: certificate
  run_list:
  - recipe[macos_test::certificate]
  verifier:
    controls:
    - certificate-install

- name: users
  run_list:
  - recipe[macos_test::new_users]
  verifier:
    controls:
    - admin-user
    - standard-user

- name: keychain
  run_list:
  - recipe[macos_test::keychain]
  verifier:
    controls:
    - keychain-creation
    - login-keychain-creation
    - default-keychain-creation
