---
driver:
  name: vagrant
  provider: parallels

provisioner:
  product_name: chef
  multiple_converge: 2

verifier:
  name: inspec
  sudo: true
  format:
  - cli
  - junit:/tmp/inspec.xml
  inspec_tests:
  - test/integration/default

platforms:
- name: el-capitan-chef13
  driver:
    box: microsoft/os-x-el-capitan
    version: 10.11.6
  provisioner:
    product_version: 13

- name: el-capitan-chef14
  driver:
    box: microsoft/os-x-el-capitan
    version: 10.11.6
  provisioner:
    product_version: 14

- name: sierra-chef13
  driver:
    box: microsoft/macos-sierra
    version: 10.12.6
  provisioner:
    product_version: 13

- name: sierra-chef14
  driver:
    box: microsoft/macos-sierra
    version: 10.12.6
  provisioner:
    product_version: 14

- name: high-sierra-chef13
  driver:
    box: microsoft/macos-high-sierra
    version: 10.13.6-v2
  provisioner:
    product_version: 13

- name: high-sierra-chef14
  driver:
    box: microsoft/macos-high-sierra
    version: 10.13.6-v2
  provisioner:
    product_version: 14

- name: mojave-chef13
  driver:
    box: microsoft/macos-mojave
    version: 10.14.01
  provisioner:
    product_version: 13

- name: mojave-chef14
  driver:
    box: microsoft/macos-mojave
    version: 10.14.01
  provisioner:
    product_version: 14

suites:
- name: default
  provisioner:
    enforce_idempotency: true
  run_list:
  - recipe[macos::disable_software_updates]
  - recipe[macos_test::preferences]
  verifier:
    controls:
    - dock-appearance
    - show-all-files
    - updates-disabled

- name: power-management
  provisioner:
    enforce_idempotency: true
  run_list:
  - recipe[macos::keep_awake]
  verifier:
    controls:
    - screensaver-disabled
    - remote-administration
    - no-sleep

- name: machine-name
  run_list:
  - recipe[macos_test::machine_name]
  verifier:
    controls:
    - nonstandard-computer-name

- name: spotlight
  provisioner:
    enforce_idempotency: true
  run_list:
  - recipe[macos_test::spotlight]
  verifier:
    controls:
    - indexing-and-searching

- name: xcode
  run_list:
  - recipe[macos_test::xcode]
  verifier:
    controls:
    - xcode-and-simulators
    - command-line-tool-sentinel

- name: certificate
  run_list:
  - recipe[macos_test::certificate]
  verifier:
    controls:
    - certificate-install

- name: users
  run_list:
  - recipe[macos_test::new_users]
  verifier:
    controls:
    - admin-user
    - standard-user
    - hidden-user

- name: delete_users
  run_list:
  - recipe[macos_test::delete_users]
  verifier:
    controls:
    - test-user

- name: keychain
  run_list:
  - recipe[macos_test::keychain]
  verifier:
    controls:
    - keychain-creation
    - login-keychain-creation
    - default-keychain-creation

- name: remote-access
  provisioner:
    enforce_idempotency: true
  run_list:
  - recipe[macos_test::remote_access]
  verifier:
    controls:
    - remote-control
