---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: true

verifier:
  name: inspec
  sudo: true

platforms:
  - name: apex/macos-10.13.3
  - name: apex/macos-10.12.6
  - name: apex/macos-10.11.6

suites:
  - name: default
    provisioner:
      multiple_converge: 3
      enforce_idempotency: true
    run_list:
      - recipe[macos::keep_awake]
      - recipe[macos_test::new_users]
      - recipe[macos::disable_software_updates]
      - recipe[macos_test::preferences]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      macos:
        disk_sleep_disabled: true

  - name: machine_name
    provisioner:
      multiple_converge: 2
      enforce_idempotency: true
    run_list:
      - recipe[macos_test::machine_name]
    verifier:
      inspec_tests:
        - test/smoke/machine_name

  - name: xcode
    run_list:
      - recipe[macos_test::xcode]
    verifier:
      inspec_tests:
        - test/smoke/xcode

  - name: spotlight
    provisioner:
      multiple_converge: 2
      enforce_idempotency: true
    run_list:
      - recipe[macos_test::spotlight]
    verifier:
      inspec_tests:
        - test/smoke/spotlight

  - name: certificate
    run_list:
      - recipe[macos_test::certificate]
    verifier:
      inspec_tests:
        - test/smoke/certificate
