---
driver:
  name: vagrant
  provider: parallels

provisioner:
  product_name: chef
  product_version: 13.8
  always_update_cookbooks: true

verifier:
  name: inspec
  sudo: true

platforms:
  - name: apex/macos-10.13.3
  - name: apex/macos-10.12.6
  - name: apex/macos-10.11.6

suites:
  - name: default
    provisioner:
      multiple_converge: 2
      enforce_idempotency: true
    run_list:
      - recipe[macos_test::new_users]
      - recipe[macos::disable_software_updates]
      - recipe[macos_test::preferences]
    verifier:
      inspec_tests:
        - test/smoke/default

  - name: keep_awake
    provisioner:
      multiple_converge: 2
      enforce_idempotency: false
    run_list:
      - recipe[macos::keep_awake]
    verifier:
      inspec_tests:
        - test/smoke/keep_awake

  - name: machine_name
    provisioner:
      multiple_converge: 2
      enforce_idempotency: true
    run_list:
      - recipe[macos_test::machine_name]
    verifier:
      inspec_tests:
        - test/smoke/machine_name

  - name: xcode
    run_list:
      - recipe[macos_test::xcode]
    verifier:
      inspec_tests:
        - test/smoke/xcode

  - name: spotlight
    provisioner:
      multiple_converge: 2
      enforce_idempotency: true
    run_list:
      - recipe[macos_test::spotlight]
    verifier:
      inspec_tests:
        - test/smoke/spotlight

  - name: certificate
    run_list:
      - recipe[macos_test::certificate]
    verifier:
      inspec_tests:
        - test/smoke/certificate
