---
driver:
  name: vagrant
  provider: parallels

provisioner:
  product_name: chef
  product_version: latest
  install_strategy: always

verifier:
  name: inspec
  sudo: true
  inspec_tests:
  - test/integration/default

platforms:
- name: apex/macos-10.11.6
- name: apex/macos-10.12.6
- name: apex/macos-10.13.3

suites:
- name: default
  run_list:
  - recipe[macos::disable_software_updates]
  - recipe[macos_test::preferences]
  verifier:
    controls:
    - dock-appearance
    - show-all-files
    - updates-disabled

- name: power-management
  run_list:
  - recipe[macos::keep_awake]
  verifier:
    controls:
    - screensaver-disabled
    - remote-administration
    - no-sleep

- name: machine-name
  run_list:
  - recipe[macos_test::machine_name]
  verifier:
    controls:
    - nonstandard-computer-name

- name: spotlight
  run_list:
  - recipe[macos_test::spotlight]
  verifier:
    controls:
    - indexing-and-searching

- name: xcode
  run_list:
  - recipe[macos_test::xcode]
  verifier:
    controls:
    - xcode-and-simulators

- name: xcode_beta
  includes:
  - apex/macos-10.13.3
  run_list:
  - recipe[macos_test::xcode_beta]
  verifier:
    controls:
    - xcode-beta

- name: certificate
  run_list:
  - recipe[macos_test::certificate]
  verifier:
    controls:
    - certificate-install

- name: users
  run_list:
  - recipe[macos_test::new_users]
  verifier:
    controls:
    - admin-user
    - standard-user
