---
driver:
  name: vagrant
  provider: parallels

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec
  sudo: true
  inspec_tests:
  - test/integration/default

platforms:
- name: apex/macos-10.11.6
- name: apex/macos-10.12.6
- name: apex/macos-10.13.3

suites:
- name: default
  run_list:
  - recipe[macos_test::new_users]
  - recipe[macos::disable_software_updates]
  - recipe[macos_test::preferences]
  - recipe[macos_test::certificate]
  verifier:
    controls:
    - dock-appearance
    - show-all-files
    - admin-user
    - standard-user
    - updates-disabled
    - certificate-install

- name: power_management
  run_list:
  - recipe[macos::keep_awake]
  verifier:
    controls:
    - screensaver-disabled
    - remote-administration
    - no-sleep

- name: machine_name
  run_list:
  - recipe[macos_test::machine_name]
  verifier:
    controls:
    - nonstandard-computer-name

- name: spotlight
  run_list:
  - recipe[macos_test::spotlight]
  verifier:
    controls:
    - indexing/searching

- name: xcode
  run_list:
  - recipe[macos_test::xcode]
  verifier:
    controls:
    - xcode/simulators
