name 'macos'
maintainer 'Copyright 2017 Microsoft. All rights reserved.'
maintainer_email 'apxlab@microsoft.com'
license 'MIT'
description 'Installs/Configures macos-cookbook'
long_description 'Installs/Configures macos-cookbook'
version '0.2.2'
chef_version '~> 13.0' if respond_to?(:chef_version)
source_url 'https://github.com/Microsoft/macos-cookbook'
issues_url 'https://github.com/Microsoft/macos-cookbook/issues'
supports 'mac_os_x'